/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0e0e0e',
        surface: '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#191a1a',
        'surface-container-high': '#1f2020',
        'surface-container-highest': '#252626',
        'surface-bright': '#2b2c2c',
        'surface-variant': '#252626',
        primary: '#c6c6c7',
        'primary-dim': '#b8b9b9',
        'primary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#d4d4d4',
        'primary-container': '#454747',
        'on-primary': '#3f4041',
        'on-primary-container': '#d0d0d0',
        'on-primary-fixed': '#3e4040',
        'on-primary-fixed-variant': '#5a5c5c',
        secondary: '#9d9da2',
        'secondary-dim': '#9d9da2',
        'secondary-fixed': '#e3e2e7',
        'secondary-fixed-dim': '#d5d4d9',
        'secondary-container': '#3a3b3f',
        'on-secondary': '#1f2024',
        'on-secondary-container': '#bfbfc4',
        'on-secondary-fixed': '#3e3f43',
        'on-secondary-fixed-variant': '#5b5b60',
        tertiary: '#faf9f9',
        'tertiary-dim': '#ebebeb',
        'tertiary-fixed': '#f4f3f3',
        'tertiary-fixed-dim': '#e6e5e5',
        'tertiary-container': '#ebebeb',
        'on-tertiary': '#5e5f5f',
        'on-tertiary-container': '#565757',
        'on-tertiary-fixed': '#484a4a',
        'on-tertiary-fixed-variant': '#656666',
        'on-surface': '#e7e5e5',
        'on-surface-variant': '#acabaa',
        'on-background': '#e7e5e5',
        outline: '#767575',
        'outline-variant': '#484848',
        'inverse-surface': '#fcf9f8',
        'inverse-on-surface': '#565555',
        'inverse-primary': '#5e5f60',
        error: '#ee7d77',
        'error-dim': '#bb5551',
        'error-container': '#7f2927',
        'on-error': '#490106',
        'on-error-container': '#ff9993',
        'surface-tint': '#c6c6c7',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
  },
}
